### ISSUE TITLE
Não consegui rodar o projeto

### ISSUE THREAD

**Issue by ralbertini** [pabloruan0710/covid19-ios#1]
Olá!
Fiz o clone mas não consegui abrir e rodar o projeto?

Tem algum comando para rodar no terminal, algo para fazer com as dependências?
É para ser o usado o *.xcodeproj ou *.xcworkspace?

Veja ai que se der posso contribuir em algo. 

<img width="1440" alt="Captura de Tela 2020-04-11 às 11 23 35" src="https://user-images.githubusercontent.com/43758752/79046376-016ffe00-7be7-11ea-9e42-ae5665c6db6a.png">

**Comment by pabloruan0710** [comment]
Opa, tranquilo?

Então você abre o workspace, porém tem que rodar um pod install na pasta do projeto antes, pois tem dependências do cocoapods.

Qualquer duvida

62982264220 zap

Sent from my iPhone

On 11 Apr 2020, at 11:25, Ronaldo Albertini <notifications@github.com> wrote:

﻿

Olá!
Fiz o clone mas não consegui abrir e rodar o projeto?

Tem algum comando para rodar no terminal, algo para fazer com as dependências?
É para ser o usado o *.xcodeproj ou *.xcworkspace?

Veja ai que se der posso contribuir em algo.

[Captura de Tela 2020-04-11 às 11 23 35]<https://user-images.githubusercontent.com/43758752/79046376-016ffe00-7be7-11ea-9e42-ae5665c6db6a.png>

**Comment by ralbertini** [comment]
Ah, agora funcionou!
Valeu!
